##
## Makefile for my_printf in /home/dupard_e/rendus/PSU_2014_my_printf
## 
## Made by Erwan Dupard
## Login   <dupard_e@epitech.net>
## 
## Started on  Fri Nov 14 12:58:35 2014 Erwan Dupard
## Last update Fri Nov 14 13:00:16 2014 Erwan Dupard
##

library: 
	make -C lib/my re

all: library

clean:
	make -C lib/my clean

fclean:
	make -C lib/my fclean

re: all

.PHONY: library all clean fclean
